{
 "title": "1. FTT_AWS_IDC_server_resource-dashboard",
 "description": "An aesthetic dashboard for Node Exporter beginners and learners, or light users.",
 "tags": [
  "Node Exporter",
  "windows Exporter",
  "mimir",
  "aws",
  "hyper-v"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(up,job)" } },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(up{job=\"$job\"},instance)"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   },
   {
    "name": "node_short",
    "label": "node_short",
    "query": {
     "query": "label_values(up{instance=\"$node\"},instance)"
    }
   },
   { "name": "filter", "label": "Filter" },
   {
    "name": "severity",
    "label": "severity",
    "query": "info|notice , warn|warning , error|fail|critical|crit|fatal"
   }
  ]
 },
 "panels": [
  { "title": "Service system Dashboard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance Overview",
   "type": "table",
   "description": "Customised by @SLOMO / TPCTPCTPC@GitHub",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\n  # CPU 사용률 - NaN 방지\n  (1 - (1 - clamp_min(clamp_max((\n    avg by (instance)(rate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[$__rate_interval])) or\n    avg by (instance)(rate(windows_cpu_time_total{job=\"$job\", mode=\"idle\"}[$__rate_interval]))\n  ), 1), 0)) ^ 1.1) ^ (1/2) * 0.5 + \n  \n  # 메모리 사용률 - NaN 방지\n  (1 - (1 - clamp_min(clamp_max((\n    avg by (instance)(node_memory_MemAvailable_bytes{job=\"$job\"} / node_memory_MemTotal_bytes{job=\"$job\"}) or\n    avg by (instance)(windows_os_physical_memory_free_bytes{job=\"$job\"} / windows_cs_physical_memory_bytes{job=\"$job\"})\n  ), 1), 0)) ^ 2) ^ (1/2) * 0.3 + \n  \n  # 디스크 사용률 - NaN 방지\n  (1 - clamp_max(clamp_min((\n    max by (instance)(rate(node_disk_io_time_seconds_total{job=\"$job\"}[$__rate_interval])) or\n    (1 - min by (instance)(rate(windows_logical_disk_idle_seconds_total{job=\"$job\"}[$__rate_interval])))\n  ), 0), 1) ^ 1.05) ^ (1/1.5) * 0.2\n) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$job\"} or windows_cs_physical_memory_bytes{job=\"$job\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "(1 - (\r\n  (node_memory_MemAvailable_bytes{job=\"$job\"} / node_memory_MemTotal_bytes{job=\"$job\"}) or\r\n  (windows_os_physical_memory_free_bytes{job=\"$job\"} / windows_cs_physical_memory_bytes{job=\"$job\"})\r\n)) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "clamp_min((1 - avg(\r\n  rate(node_cpu_seconds_total{job=\"$job\", mode=\"idle\"}[$__rate_interval]) or\r\n  rate(windows_cpu_time_total{job=\"$job\", mode=\"idle\"}[$__rate_interval])\r\n) by (instance)) * 100, 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\r\n  node_filesystem_avail_bytes{job=\"$job\"} or\r\n  windows_logical_disk_free_bytes{job=\"$job\"}\r\n) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  (irate(node_network_transmit_bytes_total{job=\"$job\", device=~\"(eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*)\"}[$__rate_interval]) * 8) or\r\n  (irate(windows_net_bytes_sent_total{job=\"$job\"}[$__rate_interval]) * 8)\r\n) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(\r\n  (irate(node_network_receive_bytes_total{job=\"$job\", device!~\"lo|docker.*|br-.*|veth.*\"}[$__rate_interval]) * 8) or\r\n  (irate(windows_net_bytes_received_total{job=\"$job\", nic!~\".*Loopback.*|.*Virtual.*|.*isatap.*|.*Teredo.*\"}[$__rate_interval]) * 8)\r\n) by (instance)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (node_netstat_Tcp_CurrEstab{job=\"$job\"})\r\nor\r\nsum by (instance) (windows_tcp_connections_established{job=\"$job\"})\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (\r\n  rate(node_netstat_Tcp_RetransSegs{job=\"$job\"}[$__rate_interval])\r\n)\r\nor\r\nsum by (instance) (\r\n  rate(windows_tcp_segments_retransmitted_total{job=\"$job\"}[$__rate_interval])\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(time() - node_boot_time_seconds{job=\"$job\"})\r\nor\r\n(time() - windows_system_boot_time_timestamp{job=\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Overall Traffic Usage (Approx.)",
   "type": "timeseries",
   "description": "This metric provides relatively accurate results within 6-hour period.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"$job\", instance=~\".*\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|wlnet.*\"}[$__rate_interval])) * 10\r\nor\r\nsum(irate(windows_net_bytes_sent_total{job=\"$job\", instance=~\".*\", nic!~\"isatap.*|VPN.*\"}[$__rate_interval])) * 10",
     "legendFormat": "Upload"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job=\"$job\", instance=~\".*\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|wlnet.*\"}[$__rate_interval])) * 10\r\nor\r\nsum(irate(windows_net_bytes_received_total{job=\"$job\", instance=~\".*\", nic!~\"isatap.*|VPN.*\"}[$__rate_interval])) * 10",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job=\"$job\", instance=~\".*\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|wlnet.*\"}[$__rate_interval]) + \r\n    irate(node_network_receive_bytes_total{job=\"$job\", instance=~\".*\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|wlnet.*\"}[$__rate_interval])) * 10\r\nor\r\nsum(irate(windows_net_bytes_sent_total{job=\"$job\", instance=~\".*\", nic!~\"isatap.*|VPN.*\"}[$__rate_interval]) + \r\n    irate(windows_net_bytes_received_total{job=\"$job\", instance=~\".*\", nic!~\"isatap.*|VPN.*\"}[$__rate_interval])) * 10",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Connection & Traffic Summary",
   "type": "stat",
   "description": "Last modified: 23:58, December 3, 2024",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"$job\"} == 1)",
     "legendFormat": "Active Instance(s)"
    },
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{job=\"$job\"})\r\nor\r\nsum(windows_system_threads{job=\"$job\"})",
     "legendFormat": "All Connections"
    },
    {
     "expr": "(sum(irate(node_network_receive_bytes_total{job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|wlnet.*\"}[$__rate_interval]) + irate(node_network_transmit_bytes_total{job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|wlnet.*\"}[$__rate_interval]))) * 8\r\nor\r\n(sum(irate(windows_net_bytes_received_total{job=\"$job\", nic!~\"isatap.*|VPN.*\"}[$__rate_interval]) + irate(windows_net_bytes_sent_total{job=\"$job\", nic!~\"isatap.*|VPN.*\"}[$__rate_interval]))) * 8",
     "legendFormat": "Total Throughput"
    }
   ]
  },
  {
   "title": "Aggregate System Load [5m]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load5{job=\"$job\"}\r\nor\r\n(avg by (instance) (rate(windows_cpu_time_total{job=\"$job\", mode!=\"idle\"}[$__rate_interval])) * 10)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "1", "legendFormat": "baseline" }
   ]
  },
  {
   "type": "histogram",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\nirate(node_network_transmit_bytes_total{job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[$__rate_interval]) * 8 + \r\nirate(node_network_receive_bytes_total{job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[$__rate_interval]) * 8\r\nor\r\nirate(windows_net_bytes_sent_total{job=\"$job\", nic!~\"isatap.*|VPN.*\"}[$__rate_interval]) * 8 + \r\nirate(windows_net_bytes_received_total{job=\"$job\", nic!~\"isatap.*|VPN.*\"}[$__rate_interval]) * 8\r\n) * 8",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Aggregate Transmit Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  irate(node_network_transmit_bytes_total{\r\n    job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"\r\n  }[$__rate_interval])\r\n  or\r\n  irate(windows_net_bytes_sent_total{\r\n    job=\"$job\"\r\n  }[$__rate_interval])\r\n) * 8\r\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall Established & TIME_WAIT Connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_netstat_Tcp_CurrEstab{job=\"$job\"})\r\nor\r\nsum(windows_system_threads{job=\"$job\"}) * 0.1",
     "legendFormat": "Current Established"
    },
    {
     "expr": "sum(node_sockstat_TCP_tw{job=\"$job\"})\r\nor\r\n(sum(windows_system_context_switches_total{job=\"$job\"}) * 0)",
     "legendFormat": "TIME_WAIT"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))\r\nor\r\nsum(increase(windows_net_bytes_sent_total{job=\"$job\", nic!~\"isatap.*|VPN.*\"}[30d]))",
     "legendFormat": "Transmit Bandwidth"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))\r\nor\r\nsum(increase(windows_net_bytes_received_total{job=\"$job\", nic!~\"isatap.*|VPN.*\"}[30d]))",
     "legendFormat": "Receive Bandwidth"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d])) + \r\nsum(increase(node_network_receive_bytes_total{job=\"$job\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))\r\nor\r\nsum(increase(windows_net_bytes_sent_total{job=\"$job\", nic!~\"isatap.*|VPN.*\"}[30d])) + \r\nsum(increase(windows_net_bytes_received_total{job=\"$job\", nic!~\"isatap.*|VPN.*\"}[30d]))",
     "legendFormat": "30-Day Bandwidth"
    }
   ]
  },
  { "title": "〔NODE INFO〕↘️ $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{job=\"$job\", instance=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))\r\nor\r\nsum(increase(windows_net_bytes_sent_total{job=\"$job\", instance=\"$node\", nic!~\"isatap.*|VPN.*\"}[30d]))",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum(increase(node_network_receive_bytes_total{job=\"$job\", instance=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))\r\nor\r\nsum(increase(windows_net_bytes_received_total{job=\"$job\", instance=\"$node\", nic!~\"isatap.*|VPN.*\"}[30d]))",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{job=\"$job\", instance=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d])) + \r\nsum(increase(node_network_receive_bytes_total{job=\"$job\", instance=\"$node\", device=~\"eth.*|ens.*|eno.*|enp.*|enx.*|enX.*|wlan.*|venet.*\"}[30d]))\r\nor\r\nsum(increase(windows_net_bytes_sent_total{job=\"$job\", instance=\"$node\", nic!~\"isatap.*|VPN.*\"}[30d])) + \r\nsum(increase(windows_net_bytes_received_total{job=\"$job\", instance=\"$node\", nic!~\"isatap.*|VPN.*\"}[30d]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Average System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "node_load1{job=\"$job\", instance=\"$node\"}\r\nor\r\n(avg(rate(windows_cpu_time_total{job=\"$job\", instance=\"$node\", mode!=\"idle\"}[$__rate_interval])) * 10)",
     "legendFormat": "1m"
    },
    {
     "expr": "node_load5{job=\"$job\", instance=\"$node\"}\r\nor\r\n(avg(rate(windows_cpu_time_total{job=\"$job\", instance=\"$node\", mode!=\"idle\"}[$__rate_interval])) * 10)",
     "legendFormat": "5m"
    },
    {
     "expr": "node_load15{job=\"$job\", instance=\"$node\"}\r\nor\r\n(avg(rate(windows_cpu_time_total{job=\"$job\", instance=\"$node\", mode!=\"idle\"}[$__rate_interval])) * 10)",
     "legendFormat": "15m"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"$job\", instance=\"$node\", mode=\"system\"}) by (instance)\r\nor\r\ncount(windows_cpu_core_frequency_mhz{job=\"$job\", instance=\"$node\"}) by (instance)",
     "legendFormat": "CPU Cores"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"$job\", instance=\"$node\", device!~'rootfs'} - node_filesystem_avail_bytes{job=\"$job\", instance=\"$node\", device!~'rootfs'})\r\nor\r\n(windows_logical_disk_size_bytes{job=\"$job\", instance=\"$node\"} - windows_logical_disk_free_bytes{job=\"$job\", instance=\"$node\"})",
     "legendFormat": "{{mountpoint}}{{volume}} "
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"}\r\nor\r\nwindows_os_visible_memory_bytes{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\", job=\"$job\"} - node_memory_MemFree_bytes{instance=\"$node\", job=\"$job\"} - (node_memory_Cached_bytes{instance=\"$node\", job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\", job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\", job=\"$job\"})\r\nor\r\nwindows_os_visible_memory_bytes{instance=\"$node\", job=\"$job\"} - windows_os_physical_memory_free_bytes{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\", job=\"$job\"} + node_memory_Buffers_bytes{instance=\"$node\", job=\"$job\"} + node_memory_SReclaimable_bytes{instance=\"$node\", job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=\"$node\", job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$node\", job=\"$job\"})\r\nor\r\n(windows_os_virtual_memory_bytes{instance=\"$node\", job=\"$job\"} - windows_os_virtual_memory_free_bytes{instance=\"$node\", job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "CPU Activity Analysis",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\", job=\"$job\", mode=\"system\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\", job=\"$job\"}) by (cpu)))\r\nor\r\navg(rate(windows_cpu_time_total{instance=\"$node\", job=\"$job\", mode=\"privileged\"}[$__rate_interval]))",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\", job=\"$job\", mode=\"user\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\", job=\"$job\"}) by (cpu)))\r\nor\r\navg(rate(windows_cpu_time_total{instance=\"$node\", job=\"$job\", mode=\"user\"}[$__rate_interval]))",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\", job=\"$job\", mode=\"iowait\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\", job=\"$job\"}) by (cpu)))",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\", job=\"$job\", mode=~\".*irq\"}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\", job=\"$job\"}) by (cpu)))\r\nor\r\navg(rate(windows_cpu_time_total{instance=\"$node\", job=\"$job\", mode=\"interrupt\"}[$__rate_interval]))",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{instance=\"$node\", job=\"$job\", mode!='idle', mode!='user', mode!='system', mode!='iowait', mode!='irq', mode!='softirq'}[$__rate_interval])) / scalar(count(count(node_cpu_seconds_total{instance=\"$node\", job=\"$job\"}) by (cpu)))\r\nor\r\navg(rate(windows_cpu_time_total{instance=\"$node\", job=\"$job\", mode!=\"idle\", mode!=\"user\", mode!=\"privileged\", mode!=\"interrupt\"}[$__rate_interval]))",
     "legendFormat": "Busy Other"
    }
   ]
  },
  {
   "title": "Partition Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(\r\n  node_filesystem_size_bytes{\r\n    job=\"$job\", instance=\"$node\",\r\n    fstype=~\"ext.|xfs|nfs\", mountpoint!~\".*pod.*\"\r\n  }\r\n)\r\nor\r\n(\r\n  label_replace(\r\n    label_replace(\r\n      label_replace(\r\n        windows_logical_disk_size_bytes{job=\"$job\", instance=\"$node\"},\r\n        \"device\", \"$1\", \"volume\", \"(.*)\"\r\n      ),\r\n      \"mountpoint\", \"$1\", \"volume\", \"(.*)\"\r\n    ),\r\n    \"fstype\", \"ntfs\", \"volume\", \".*\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\r\n  node_filesystem_free_bytes{\r\n    job=\"$job\", instance=\"$node\",\r\n    fstype=~\"ext.|xfs|nfs\", mountpoint!~\".*pod.*\"\r\n  }\r\n)\r\nor\r\n(\r\n  label_replace(\r\n    label_replace(\r\n      label_replace(\r\n        windows_logical_disk_free_bytes{job=\"$job\", instance=\"$node\"},\r\n        \"device\", \"$1\", \"volume\", \"(.*)\"\r\n      ),\r\n      \"mountpoint\", \"$1\", \"volume\", \"(.*)\"\r\n    ),\r\n    \"fstype\", \"ntfs\", \"volume\", \".*\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  (node_filesystem_size_bytes{job=\"$job\", instance=\"$node\", fstype=~\"ext.|xfs|nfs\", mountpoint!~\".*pod.*\"}\n   - node_filesystem_free_bytes{job=\"$job\", instance=\"$node\", fstype=~\"ext.|xfs|nfs\", mountpoint!~\".*pod.*\"})\n  * 100\n  / node_filesystem_size_bytes{job=\"$job\", instance=\"$node\", fstype=~\"ext.|xfs|nfs\", mountpoint!~\".*pod.*\"}\n)\nor\n(\n  (\n    label_replace(label_replace(windows_logical_disk_size_bytes{job=\"$job\", instance=\"$node\"}, \"device\",\"$1\",\"volume\",\"(.*)\"), \"mountpoint\",\"$1\",\"volume\",\"(.*)\")\n    - label_replace(label_replace(windows_logical_disk_free_bytes{job=\"$job\", instance=\"$node\"}, \"device\",\"$1\",\"volume\",\"(.*)\"), \"mountpoint\",\"$1\",\"volume\",\"(.*)\")\n  )\n  * 100\n  / label_replace(label_replace(windows_logical_disk_size_bytes{job=\"$job\", instance=\"$node\"}, \"device\",\"$1\",\"volume\",\"(.*)\"), \"mountpoint\",\"$1\",\"volume\",\"(.*)\")\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Read/Write Rate",
   "type": "timeseries",
   "description": "Read + / Write -",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"$job\", instance=\"$node\"}[$__rate_interval])\r\nor\r\nirate(windows_logical_disk_read_bytes_total{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}{{volume}}_read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{job=\"$job\", instance=\"$node\"}[$__rate_interval])\r\nor\r\nirate(windows_logical_disk_write_bytes_total{job=\"$job\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{device}}{{volume}}_write"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{job=\"$job\", instance=\"$node\"})\r\nor\r\navg(time() - windows_system_boot_time_timestamp{job=\"$job\", instance=\"$node\"})",
     "legendFormat": "⏱️ Uptime"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"$job\", instance=\"$node\", mode=\"system\"})\r\nor\r\ncount(windows_cpu_core_frequency_mhz{job=\"$job\", instance=\"$node\"})",
     "legendFormat": "💎 Core(s)"
    },
    {
     "expr": "max(node_filesystem_size_bytes{job=\"$job\", instance=\"$node\"})\r\nor\r\nmax(windows_logical_disk_size_bytes{job=\"$job\", instance=\"$node\"})",
     "legendFormat": "💾 Disk Size"
    },
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"$job\", instance=\"$node\"})\r\nor\r\nsum(windows_os_visible_memory_bytes{job=\"$job\", instance=\"$node\"})",
     "legendFormat": "🫙 Memory Total"
    }
   ]
  },
  {
   "title": "Network Socket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=\"$node\"}\r\nor\r\nwindows_tcp_connections_state_count{instance=\"$node\", state=\"established\"}\r\n",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "sum by () (rate(node_netstat_Tcp_RetransSegs{instance=\"$node\"}[$__rate_interval]))\r\nor\r\nsum by () (rate(windows_tcp_segments_retransmitted_total{instance=\"$node\"}[$__rate_interval]))\r\n",
     "legendFormat": "Tcp_RetransSegs"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=\"$node\"}\r\nor\r\nsum by () (windows_tcp_connections_state_count{instance=\"$node\", state!=\"closed\"})\r\n",
     "legendFormat": "sockets_used"
    },
    {
     "expr": "sum by () (rate(node_netstat_Tcp_InSegs{instance=\"$node\"}[$__rate_interval]))\r\nor\r\nsum by () (rate(windows_tcp_segments_received_total{instance=\"$node\"}[$__rate_interval]))\r\n",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "sum by () (rate(node_netstat_Tcp_OutSegs{instance=\"$node\"}[$__rate_interval]))\r\nor\r\nsum by () (rate(windows_tcp_segments_sent_total{instance=\"$node\"}[$__rate_interval]))\r\n",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=\"$node\"}\r\nor\r\nwindows_tcp_connections_state_count{instance=\"$node\", state=\"time_wait\"}\r\n",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "sum by () (rate(node_netstat_TcpExt_ListenDrops{instance=\"$node\"}[$__rate_interval]))\r\nor\r\nsum by () (\r\n  rate(windows_tcp_connection_failures_total{instance=\"$node\"}[$__rate_interval])\r\n+ rate(windows_tcp_connections_reset_total{instance=\"$node\"}[$__rate_interval])\r\n)\r\n",
     "legendFormat": "TcpExt_ListenDrops"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=\"$node\"}\r\nor\r\nsum by () (rate(windows_udp_datagrams_received_total{instance=\"$node\"}[$__rate_interval]))\r\n",
     "legendFormat": "UDP_inuse"
    }
   ]
  },
  {
   "title": "Network Bandwidth Usage",
   "type": "timeseries",
   "description": "Receive + / Transmit -",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\nirate(node_network_receive_bytes_total{job=\"$job\", instance=\"$node\"}[$__rate_interval]) * 8\r\nor\r\nirate(windows_net_bytes_received_total{job=\"$job\", instance=\"$node\"}[$__rate_interval]) * 8\r\n) * 8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "sum by (instance) (\r\nirate(node_network_transmit_bytes_total{job=\"$job\", instance=\"$node\"}[$__rate_interval]) * 8\r\nor\r\nirate(windows_net_bytes_sent_total{job=\"$job\", instance=\"$node\"}[$__rate_interval]) * 8\r\n) * 8\r\n",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  { "title": "〔Logs & Alerting〕↘️ $node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "System logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{hostname=~\"(?i)^$node_short(\\\\..*)?$\"}\r\n| logfmt\r\n| regexp \"(?:^|\\\\s)hostname:(?P<hostname>\\\\S+).*?service_name:(?P<service_name>\\\\S+)(?:.*?(?:event_id|id):(?P<event_id>\\\\S+))?\"\r\n| regexp \"(?P<raw>.*)\"\r\n|~ \"(?i)(${severity})\"\r\n|~ \"${filter}\"\r\n| label_format node=\"{{.hostname}}\", svc=\"{{or .service_name .program .app}}\", eid=\"{{.event_id}}\"\r\n| line_format \"{{.node}} {{.svc}}{{if .eid}} Ev{{.eid}}{{end}} — {{or .msg .message .raw .entry}}\"\r\n"
    },
    {
     "direction": "backward",
     "expr": "{computer=~\"(?i)^$node_short(\\\\..*)?$\"}\r\n| json | logfmt\r\n| label_format node=\"{{ .computer }}\",\r\n               svc=\"{{ if .service_name }}{{ .service_name }}{{ else if .program }}{{ .program }}{{ else if .app }}{{ .app }}{{ else if .channel }}{{ .channel }}{{ end }}\",\r\n               eid=\"{{ if .event_id }}{{ .event_id }}{{ else if .eid }}{{ .eid }}{{ else if .id }}{{ .id }}{{ end }}\",\r\n               level=\"{{- if eq .levelText `Critical` -}}critical{{- else if eq .levelText `Error` -}}error{{- else if eq .levelText `Warning` -}}warning{{- else if eq .levelText `Information` -}}info{{- else -}}info{{- end -}}\"\r\n| line_format \"{{ .node }} {{ .svc }}{{ if .eid }} Ev{{ .eid }}{{ end }} — {{ if .Message }}{{ .Message }}{{ else if .message }}{{ .message }}{{ else if .msg }}{{ .msg }}{{ else if .rendered_message }}{{ .rendered_message }}{{ else if .event_data }}{{ .event_data }}{{ else if .EventData }}{{ .EventData }}{{ else if .raw }}{{ .raw }}{{ else if .entry }}{{ .entry }}{{ end }}\"\r\n"
    }
   ]
  },
  {
   "title": "Alert history",
   "type": "logs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{from=\"state-history\"}\r\n| json ruleTitle=\"ruleTitle\", current=\"current\", previous=\"previous\",\r\n      inst=\"labels.instance\", inst2=\"labels_instance\",\r\n      vA=\"values.A\", vB=\"values.B\", vC=\"values.C\",\r\n      th=\"labels.threshold\", ann_th=\"annotations.threshold\", unit=\"annotations.unit\"\r\n| __error__ = \"\"\r\n| (inst=~\"(?i)^$node_short$\" or inst2=~\"(?i)^$node_short$\")\r\n|~ \"$filter\"\r\n| regexp `\"values\":\\{\"A\":(?P<valShort>\\d+(?:\\.\\d{0,2})?)`\r\n| regexp `\"threshold\":(?P<thShort>\\d+(?:\\.\\d{0,2})?)`\r\n| line_format \"{{if eq .current \\\"Alerting\\\"}}🔥 ALERT{{else if eq .current \\\"Pending\\\"}}⏳ PENDING{{else}}✅ RESOLVED{{end}} – {{.ruleTitle}} @{{or .inst .inst2}} (val={{or .valShort .vA .vB .vC}}{{if or .thShort .th .ann_th}} / th={{or .thShort .th .ann_th}}{{end}}{{if .unit}} {{.unit}}{{end}}, prev={{.previous}})\""
    }
   ]
  },
  { "title": "Alert status", "type": "alertlist", "gridPos": { "h": 11, "w": 12, "x": 12, "y": 67 } }
 ]
}