{
 "title": "2. FTT_AWS_RDS_Elasticache_Database-dashboard",
 "description": "Visualize Database metrics",
 "tags": [
  "AWS RDS",
  "AWS Elasticache",
  "MySQL",
  "MS SQL Server",
  "Redis"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Account_ID", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Database List",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dimension_DBInstanceIdentifier!=\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "aws_elasticache_cpuutilization_average{dimension_CacheNodeId!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AWS RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "CPUUtilization",
   "type": "timeseries",
   "description": "CPU 사용률의 백분율",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{dimension_DBInstanceIdentifier!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DatabaseConnections",
   "type": "timeseries",
   "description": "인스턴스에 대한 클라이언트 네트워크 연결 수",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "aws_rds_database_connections_average{dimension_DBInstanceIdentifier!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FreeableMemory",
   "type": "timeseries",
   "description": "사용 가능한 랜덤 액세스 메모리의 용량",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{dimension_DBInstanceIdentifier!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ReadIOPS",
   "type": "timeseries",
   "description": "초당 평균 디스크 읽기 I/O 작업 수",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "aws_rds_read_iops_sum{dimension_DBInstanceIdentifier!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WriteIOPS",
   "type": "timeseries",
   "description": "초당 평균 디스크 쓰기 I/O 작업 수",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "aws_rds_write_iops_sum{dimension_DBInstanceIdentifier!=\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ReadLatency",
   "type": "timeseries",
   "description": "디스크 I/O 작업당 소요된 평균 시간",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_rds_read_latency_average{dimension_DBInstanceIdentifier!=\"\"}  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WriteLatency",
   "type": "timeseries",
   "description": "디스크 I/O 작업당 소요된 평균 시간",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "aws_rds_write_latency_average{dimension_DBInstanceIdentifier!=\"\"}  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AWS Elasticache",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "FreeableMemory",
     "type": "timeseries",
     "description": "사용 가능한 여유 메모리의 양",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aws_elasticache_freeable_memory_average{dimension_CacheNodeId!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CurrConnections",
     "type": "timeseries",
     "description": "클라이언트 연결 수",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aws_elasticache_curr_connections_average{dimension_CacheNodeId!=\"\"} ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "BytesUsedForCache",
     "type": "timeseries",
     "description": "Redis에 할당된 총 바이트 수",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "aws_elasticache_bytes_used_for_cache_average{dimension_CacheNodeId!=\"\"} ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPUUtilization",
     "type": "timeseries",
     "description": "(vCPU가 2개 이하인 경우)\nCPU 사용률",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aws_elasticache_cpuutilization_average{dimension_CacheNodeId!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EngineCPUUtilization",
     "type": "timeseries",
     "description": "(vCPU가 3개 이상인 경우)\n엔진 스레드의 CPU 사용률",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "aws_elasticache_engine_cpuutilization_average{dimension_CacheNodeId!=\"\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}