version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: jsj-jenkins:terraform
    user: "0:0"          # Run as root to allow timestamp updates on drvfs volumes
    container_name: jsj-jenkins-server
    ports:
      - "8080:8080"      # Jenkins 웹 UI
      - "50000:50000"    # Jenkins 에이전트 연결
    volumes:
      - ./jenkins-data/jenkins_home:/var/jenkins_home  # Jenkins 전체 홈 디렉터리
    environment:
      - TZ=Asia/Seoul
    networks:
      - jenkins_default
    restart: unless-stopped

networks:
  jenkins_default:
    driver: bridge
